### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by jharej** [marceloschmitt/pbltool#2]
Hi,

is there any plan to upgrade this plugin for Moodle 3.2?

thanks for reply

**Comment by marceloschmitt** [comment]
There was not until now. Can you give two weeks?

**Comment by jharej** [comment]
Sure. Thanks for quick reply
Bye, janko

14. mar. 2017 12:39 pop. je oseba "Marcelo A. Rauh Schmitt" <
notifications@github.com> napisala:

**Comment by marceloschmitt** [comment]
I did it. And I am going to improve de plugin.
